### ISSUE TITLE
Fatal Error in clean install as timber controller is missing

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/theme#2]
```
Fatal error: Uncaught Error: Class 'App\Controllers\Timber' not found in /srv/users/serverpilot/apps/chemistry/public/wp-content/themes/chemistry/app/Controllers/AppController.php:82 Stack trace: #0 /srv/users/serverpilot/apps/chemistry/public/wp-includes/class-wp-hook.php(298): App\Controllers\AppController->display_app_header_menu('') #1 /srv/users/serverpilot/apps/chemistry/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #2 /srv/users/serverpilot/apps/chemistry/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /srv/users/serverpilot/apps/chemistry/public/wp-content/themes/chemistry/header.php(107): do_action('app_header_menu') #4 /srv/users/serverpilot/apps/chemistry/public/wp-includes/template.php(688): require_once('/srv/users/serv...') #5 /srv/users/serverpilot/apps/chemistry/public/wp-includes/template.php(647): load_template('/srv/users/serv...', true) #6 /srv/users/serverpilot/apps/chemistry/public/wp-includes/general-template.php(45): locate_template(Array, true) #7 /s in /srv/users/serverpilot/apps/chemistry/public/wp-content/themes/chemistry/app/Controllers/AppController.php on line 82
```

**Comment by terence1990** [comment]
Use Timber;

after namespace declaration but before class declaration

**Comment by mattpilott** [comment]
Needs both of these so i think add them to the appcontroller by default

```
use Timber;
use TimberMenu;

```

**Comment by terence1990** [comment]
ok
